numbers=[1,10,5,16,4,9,10]
letters=['a','g','s','b','y','a','s']
val=min(numbers)#1
val=max(numbers)#16
val=min(letters)#a
val=max(letters)#y
val=numbers[3:6]#[16,4,9]
print(val)
val=numbers[:3]#[1,10,5]
print(val)
val=numbers[4:]#[4,9,10]
print(val)
print(numbers)
numbers[4]=40
print(numbers)
numbers.append(49)
print(numbers)
numbers.append(59)
print(numbers)
numbers.insert(3,78)
print(numbers)
numbers.insert(-1,52)
numbers.pop(0)
print(numbers)
numbers.pop(-1)
print(numbers)
numbers.pop()#pop icin indexe bakariz remove da elemana bakariz
print(numbers)
numbers.remove(49)#remove un icindeki eleman listede olmazsa hata verir
print(numbers)
numbers.sort()
numbers.reverse()
letters.sort()
letters.reverse()
print(numbers)
print(letters)
print(len(numbers))
print(len(letters))
print(numbers.count(10))
print(letters.count('a'))

